### ISSUE TITLE
[BUG] permission denied!

### ISSUE THREAD

**Issue by bineetNaidu** [bradtraversy/passgen#1]
## :bug: Bug Report!
After generating a password and save it to `passwords.txt`, i can't open the file as its errors out! saying that `PERMISSION DENIED` . 

- OS: ubuntu 20.* (linux)

**Comment by dasmido** [comment]
the file passwords.txt is protected, if you want to open it, in command line write, `sudo vi passwords.txt` tested in Ubuntu 21.04

**Comment by bineetNaidu** [comment]
Thank for the information. It Worked!
